services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rbdnti_web
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data/db:/app/rbdnti/db
      - ./data/media:/app/rbdnti/media
      - ./data/staticfiles:/app/rbdnti/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    container_name: rbdnti_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/staticfiles:/static:ro
      - ./data/media:/media:ro
    depends_on:
      - web
